<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ui_provider"
 *
 * Auto generated by Extension Builder 2019-10-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'u+i | Provider',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sebastian Swan',
    'author_email' => 'seswan@uandi.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.26',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
